
# Top-level settings
settings:
    traj_type: 'interp'  # Types include: 'waveform', 'interp'


# Place all of the type-specific settings in here
config:
    interp_type: none   # can be: 'linear', 'cubic', 'none'
    setpoints:
        # [time, position [x,y,z], orientation [x,y,z]]
        main:
            - [0.00,   0,0,0, 0,0,0.0]     #1 middle, 2 right(from thumb), 3 thumb, 4 left(from thumb)
            - [2.00,   0,0,0, 0,0,0.0] 
            - [4.00,   0,0,0, 0,0,0.0]  
            - [6.00,   0,0,0, 0,0,0.0]
            - [8.00,   0,0,0, 0,0,0.0]
            


        prefix:
            - [0.00,  0,0,0, 0,0,0]
            - [1.50,  0,0,0, 0,0,0] 
            - [2.50,  0,0,0, 0,0,0.0]     

        suffix:
            - [4.0,   0,0,0, 0,0,0]